### ISSUE TITLE
Vietnamese Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-vi#1]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, please read the [translation guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) to understand the Gatsby translation process.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Community

* [x] community/code-of-conduct (@nguyenami - #6)
    

### Tutorial

* [x] tutorial/index  (@giatuongtran9 - #5)
* [x] tutorial/part-zero (@vitokhangnguyen - #8)
* [x] tutorial/part-one (@giatuongtran9 - #9)
* [x] tutorial/part-two (@tonyvugithub - #12 )
* [x] tutorial/part-three (@dennis-IT - #11)
* [x] tutorial/part-four (@Mai-Do - #10)
* [x] tutorial/part-five (@tonyvugithub - #13)
* [x] tutorial/part-six (@dennis-IT - #15)
* [ ] tutorial/part-seven (@tonyvugithub)
* [ ] tutorial/part-eight (@Andrewnt219 - #16)
    

### Docs

* [ ] docs/index (@Mai-Do)
* [x] docs/quick-start (@phanatuan - #19)
* [ ] docs/glossary
* [ ] docs/gatsby-cli
    

#### Recipes

* [ ] docs/recipes
* [ ] docs/recipes/pages-layouts
* [ ] docs/recipes/styling-css
* [ ] docs/recipes/working-with-starters
* [ ] docs/recipes/working-with-themes
* [ ] docs/recipes/sourcing-data
* [ ] docs/recipes/querying-data
* [ ] docs/recipes/working-with-images
* [ ] docs/recipes/transforming-data
* [ ] docs/recipes/deploying-your-site

#### API Reference

* [ ] docs/api-reference
* [ ] docs/theme-api
* [ ] docs/gatsby-link
* [ ] docs/gatsby-image
* [ ] docs/gatsby-config
* [ ] docs/browser-apis
* [ ] docs/ssr-apis
* [ ] docs/api-files
* [ ] docs/api-files-gatsby-config
* [ ] docs/api-files-gatsby-browser
* [ ] docs/api-files-gatsby-node
* [ ] docs/api-files-gatsby-ssr
* [ ] docs/actions
* [ ] docs/graphql-api
* [ ] docs/node-apis
* [ ] docs/node-api-helpers
* [ ] docs/node-model
* [ ] docs/node-interface
* [ ] docs/schema-customization
* [ ] docs/api-specification

**Comment by giatuongtran9** [comment]
@vitokhangnguyen Hi I want to translate ```tutorial/index```

**Comment by vitokhangnguyen** [comment]
@giatuongtran9 Go ahead! Please be aware that the links in that document are pointing to the wrong place or misleading. You can ask me anything so we can decide on where to point those links.

*Edit:* I updated your document from `docs/index` to `tutorial/index`

**Comment by jaydinsweo** [comment]
Hey, I would like to help to, I will take `community/code-of-conduct`.

**Comment by vitokhangnguyen** [comment]
@nguyenami Please go ahead, Thank you for your interest! Look forward to seeing your PR.

**Comment by giatuongtran9** [comment]
@vitokhangnguyen I will take the turorial/part-one if it still available

**Comment by vitokhangnguyen** [comment]
@giatuongtran9  Please do and go ahead!

**Comment by tonyvugithub** [comment]
@vitokhangnguyen  Hello Khang, I would like to take up tutorial/part-two

**Comment by vitokhangnguyen** [comment]
@tonyvugithub Please go ahead, I look forward to seeing your work!

@giatuongtran9 Hi, it has been a while so I want to check up on your work of `tutorial/part-one`. How is it going?

**Comment by giatuongtran9** [comment]
@vitokhangnguyen sorry I stuck with other work. I will get it up on tonight or tomorrow.

**Comment by dennis-IT** [comment]
@vitokhangnguyen Hi Khang, I'd like to take up tutorial/part-three if still available. Thanks.

**Comment by vitokhangnguyen** [comment]
@dennis-IT Hi, please go ahead! Thank you for your interest in contribution!

@giatuongtran9 It is ok. I just want to see if you were still working on it. I saw your PR. Will working on it shortly!

**Comment by Mai-Do** [comment]
@vitokhangnguyen  Hi, I'd like to take tutorial/part-four.

**Comment by vitokhangnguyen** [comment]
@Mai-Do Please do! I hope you enjoy doing the translation!

**Comment by tonyvugithub** [comment]
@vitokhangnguyen Hi Khang, can i take part 5 of the tutorial please?

**Comment by dennis-IT** [comment]
@vitokhangnguyen Hi Khang, I'd like to take part 6 of the tutorial. Thanks.

**Comment by Mai-Do** [comment]
@vitokhangnguyen Hi, I'd like to take tutorial/part 7. Thanks!

**Comment by vitokhangnguyen** [comment]
@tonyvugithub @dennis-IT @Mai-Do I appreciate your willingness to continue to help me with this project! As you just completed your first translation. let me quickly review them first so you have an idea about the translation style and I will then assign the documents to you.

Thank you for all of your efforts!

**Comment by vitokhangnguyen** [comment]
@tonyvugithub Keep up with your good work! Please go ahead with `tutorial/part-5`

**Comment by Andrewnt219** [comment]
@vitokhangnguyen Hi Khang, I'd love to help with tutorial/part-six.

**Comment by vitokhangnguyen** [comment]
Hi everyone, due to the holiday season, please forgive me for the delay and reply and translation reviews. I wish you all a Happy Holiday Season!

@dennis-IT Very good job with translation of `tutorial-part-three`, please go ahead with `tutorial.part-six` if you are still interested!

@Andrewnt219 Hi, thanks for your interest to help! Another team member has claimed `tutorial/part-six` before you did. Are you ok doing `tutorial/part-eight`? Please confirm.

**Comment by tonyvugithub** [comment]
@vitokhangnguyen: Hi Khang, i just pr for review tutorial part five. No rush on reviewing, anytime you can. In the meantime, if Andrew took part 7, can i take part 8 please? Im on a roll and just wish to keep going.

**Comment by dennis-IT** [comment]
@vitokhangnguyen Hi Khang, thanks e. I'm taking up part-6.

**Comment by vitokhangnguyen** [comment]
@dennis-IT The doc has been assigned to you. Have fun!

@tonyvugithub Since he did not confirm yet, you can go with part 7, he will do 8 when he confirms. I have assigned part 7 to you.

**Comment by Andrewnt219** [comment]
@vitokhangnguyen yes, no problem.

**Comment by vitokhangnguyen** [comment]
@Andrewnt219 Much appreciated! You have been assigned.

**Comment by Andrewnt219** [comment]
@vitokhangnguyen, Hello Khang, I've submitted part 8 but I'm not certain if I did the procedure correctly, could you check? I can also continue to work on docs/index.

**Comment by vitokhangnguyen** [comment]
@Andrewnt219 Thank you for the PR. Since you are a first-time contributor. Let me take look at your PR and leave some feedback first so you are familiar with the translation guideline. I will then assign new document to you.

**Comment by Mai-Do** [comment]
@vitokhangnguyen Hi, I'll take docs/index please. Thank you.

**Comment by phanatuan** [comment]
@vitokhangnguyen  - Hi, I could take the ` docs/quick-start` please :)

**Comment by phanatuan** [comment]
Đã submit PR cho `docs/quick-start` #19
